#
# /etc/pacman.conf - ByteOS package manager configuration
#
[options]
HoldPkg     = pacman bytekernel
Architecture = lua54
CheckSpace
ParallelDownloads = 1
SigLevel    = Never

# Repositories. A "Server" is any path reachable from the VFS.
# Drop a floppy/HDD with a /repo folder, mount it, and point Server there.

[core]
Server = /mnt/repo/core

[extra]
Server = /mnt/repo/extra

#[community]
#Server = /mnt/repo/community
