-- Everyday commands and disks.
users()
put("/tmp/a.txt", "one\ntwo\nthree\nfour\n")

test("text: head, tail, wc, grep options", function()
  eq(run("head -n 2 /tmp/a.txt"), "one\ntwo\n")
  eq(run("tail -1 /tmp/a.txt"), "four\n")
  eq(run("wc /tmp/a.txt"), "      4       4      19 /tmp/a.txt\n")
  eq(run("grep -c o /tmp/a.txt"), "3\n")
  eq(run("grep -v o /tmp/a.txt"), "three\n")
  eq(run("grep -i ONE /tmp/a.txt"), "one\n")
  local _, rc = run("grep xyz /tmp/a.txt")
  eq(rc, 1, "no match: status 1")
end)

test("touch, find, which, env", function()
  run("touch /tmp/new.txt")
  ok(file("/tmp/new.txt"), "created")
  eq(run("find /tmp -name 'n*'"), "/tmp/new.txt\n")
  eq(run("find /etc -name '*release*' -type f"), "/etc/os-release\n")
  local w = run("alias ll='ls -l'; which ls cd ll nosuch")
  has(w, "/bin/ls.lua"); has(w, "cd: shell built-in"); has(w, "ll: aliased to ls -l"); has(w, "which: no nosuch")
  eq(run("env GREETING=hi sh -c 'echo $GREETING'; echo after=$GREETING"), "hi\nafter=\n")
end)

test("df, du, free, date, hostname", function()
  has(run("df"), "Mounted on")
  ok(run("du -sh /bin"):match("^%d+%.?%d*[KM]\t/bin\n$"), "du -sh")
  has(run("free"), "Mem:")
  ok(run("date +%Y"):match("^%d%d%d%d\n$"), "date +%Y")
  run("hostname newbox")
  eq(file("/etc/hostname"), "newbox\n")
  as("bob", function() has(run("hostname evil"), "must be root") end)
end)

test("disks: mounted at boot, hotplug, mount/umount", function()
  os.execute("mkdir -p '" .. ROOT .. "/mnt'") -- init creates /mnt at boot
  disk(ROOT .. "/../floppy-test", "f1oppy01-test", "floppy")
  put("/../floppy-test/readme.txt", "on the floppy\n")
  deliver({ { "component_added", "f1oppy01-test", "filesystem" } })
  eq(run("ls /mnt"), "f1oppy01\n")
  eq(run("cat /mnt/f1oppy01/readme.txt"), "on the floppy\n")
  has(run("lsblk"), "/mnt/f1oppy01")
  run("umount /mnt/f1oppy01; mount f1oppy01 /media")
  eq(run("cat /media/readme.txt"), "on the floppy\n")
  has(run("umount /"), "cannot be unmounted")
  as("bob", function() has(run("umount /media"), "permission denied") end)
  undisk("f1oppy01-test")
  deliver({ { "component_removed", "f1oppy01-test", "filesystem" } })
  eq(run("ls /mnt"), "")
  os.execute("rm -rf '" .. ROOT .. "/../floppy-test'")
end)

test("less passes text through a pipe", function()
  eq(run("less /tmp/a.txt | wc -l"), "      4\n")
end)

test("logout leaves every shell, also a nested one", function()
  put("/tmp/nested.lua", 'local ok, rc = pcall(shell.execute, "logout")\nif not ok then error(rc, 0) end\n')
  local okRun, err = pcall(run, "/tmp/nested.lua")
  eq(okRun, false); eq(err, "__logout__")
end)

test("cp -r copies directories; several sources go into a directory", function()
  put("/tmp/src/a.txt", "a\n"); put("/tmp/src/sub/b.txt", "b\n")
  has(run("cp /tmp/src /tmp/dst"), "is a directory (use -r)")
  run("cp -r /tmp/src /tmp/dst")
  eq(file("/tmp/dst/sub/b.txt"), "b\n")
  run("mkdir /tmp/into; cp /tmp/src/a.txt /tmp/src/sub/b.txt /tmp/into")
  eq(file("/tmp/into/a.txt"), "a\n"); eq(file("/tmp/into/b.txt"), "b\n")
  has(run("cp -r /tmp/src /tmp/src/sub"), "into itself")
  has(run("cp /tmp/src/a.txt /tmp/src/sub/b.txt /tmp/none"), "is not a directory")
end)

test("mv into a directory, and directories onto another disk", function()
  put("/tmp/m/one.txt", "1\n"); put("/tmp/m/dir/two.txt", "2\n")
  run("mkdir /tmp/box; mv /tmp/m/one.txt /tmp/box")
  eq(file("/tmp/box/one.txt"), "1\n"); eq(file("/tmp/m/one.txt"), nil)
  os.execute("mkdir -p '" .. ROOT .. "/mnt'")
  disk(ROOT .. "/../mvdisk-test", "d15cmv00-test", "other")
  deliver({ { "component_added", "d15cmv00-test", "filesystem" } })
  eq(run("mv /tmp/m/dir /mnt/d15cmv00/dir"), "", "mv output")
  eq(io.open(ROOT .. "/../mvdisk-test/dir/two.txt"):read("a"), "2\n", "copied onto the other disk")
  eq(file("/tmp/m/dir/two.txt"), nil, "original removed")
  has(run("mv /tmp/box /tmp/box/inner"), "into itself")
  os.execute("rm -rf '" .. ROOT .. "/../mvdisk-test'")
end)
