-- The text tools: seq sort uniq tee xargs sed cut tr diff basename dirname
-- sha256sum mktemp.
put("/tmp/names.txt", "carol 30\nalice 5\nbob 100\nalice 5\n")
put("/tmp/csv.txt", "id:name:shell\n1:alice:/bin/sh\n2:bob:/bin/sh\nnodelim\n")

test("seq", function()
  eq(run("seq 3"), "1\n2\n3\n")
  eq(run("seq 2 2 7"), "2\n4\n6\n")
  eq(run("seq 3 -1 1"), "3\n2\n1\n")
  eq(run("seq -s , 1 4"), "1,2,3,4\n")
  eq(run("seq -w 8 10"), "08\n09\n10\n")
  eq(run("seq 0.5 0.5 1.5"), "0.5\n1\n1.5\n")
  eq(run("seq 5 1"), "", "nothing to count")
end)

test("sort: plain, numeric, reverse, unique, by field", function()
  eq(run("sort /tmp/names.txt"), "alice 5\nalice 5\nbob 100\ncarol 30\n")
  eq(run("sort -u /tmp/names.txt"), "alice 5\nbob 100\ncarol 30\n")
  eq(run("sort -n -k 2 /tmp/names.txt"), "alice 5\nalice 5\ncarol 30\nbob 100\n")
  eq(run("sort -rn -k 2 /tmp/names.txt"), "bob 100\ncarol 30\nalice 5\nalice 5\n")
  eq(run("sort -t : -k 2 /tmp/csv.txt"), "nodelim\n1:alice:/bin/sh\n2:bob:/bin/sh\nid:name:shell\n")
  eq(run("sort -r /tmp/names.txt | head -n 1"), "carol 30\n")
  eq(run("sort -f < /tmp/names.txt | head -n 1"), "alice 5\n")
end)

test("uniq", function()
  eq(run("sort /tmp/names.txt | uniq"), "alice 5\nbob 100\ncarol 30\n")
  eq(run("sort /tmp/names.txt | uniq -c"), "      2 alice 5\n      1 bob 100\n      1 carol 30\n")
  eq(run("sort /tmp/names.txt | uniq -d"), "alice 5\n")
  eq(run("sort /tmp/names.txt | uniq -u"), "bob 100\ncarol 30\n")
end)

test("tee", function()
  eq(run("echo hi | tee /tmp/t1 /tmp/t2"), "hi\n")
  eq(file("/tmp/t1"), "hi\n"); eq(file("/tmp/t2"), "hi\n")
  run("echo more | tee -a /tmp/t1")
  eq(file("/tmp/t1"), "hi\nmore\n")
end)

test("cut", function()
  eq(run("cut -d : -f 2 /tmp/csv.txt"), "name\nalice\nbob\nnodelim\n")
  eq(run("cut -d: -f1,3 -s /tmp/csv.txt"), "id:shell\n1:/bin/sh\n2:/bin/sh\n")
  eq(run("cut -d : -f 2- /tmp/csv.txt | head -n 2"), "name:shell\nalice:/bin/sh\n")
  eq(run("echo abcdef | cut -c 2-4"), "bcd\n")
  eq(run("echo abcdef | cut -c -2,5-"), "abef\n")
end)

test("tr", function()
  eq(run("echo hello | tr a-z A-Z"), "HELLO\n")
  eq(run("echo hello | tr -d l"), "heo\n")
  eq(run("echo 'a  b   c' | tr -s ' '"), "a b c\n")
  eq(run("echo abc | tr abc x"), "xxx\n")
  eq(run("echo 'Hi 42' | tr '[:lower:][:digit:]' '#'"), "H# ##\n")
end)

test("xargs", function()
  eq(run("echo a b c | xargs"), "a b c\n")
  eq(run("echo a b c | xargs -n 2 echo x"), "x a b\nx c\n")
  eq(run("seq 2 | xargs -I N echo [N]"), "[1]\n[2]\n")
  run("echo /tmp/t1 /tmp/t2 | xargs rm")
  ok(not file("/tmp/t1") and not file("/tmp/t2"), "xargs rm removed both")
  eq(run("echo \"it's\" | xargs echo"), "it's\n", "quotes in words survive")
  run("echo q | xargs echo > /tmp/xa")
  eq(file("/tmp/xa"), "q\n", "the command's output can be redirected")
  local _, rc = run("echo x | xargs false")
  eq(rc, 123)
end)

test("sed", function()
  eq(run("echo hello world | sed s/o/0/"), "hell0 world\n")
  eq(run("echo hello world | sed s/o/0/g"), "hell0 w0rld\n")
  eq(run("echo hello world | sed s/o/0/2"), "hello w0rld\n")
  eq(run("echo a-b | sed 's/(%a)-(%a)/\\2-\\1 [&]/'"), "b-a [a-b]\n")
  eq(run("echo x | sed 's/x/a\\&b/'"), "a&b\n", "an escaped & is a plain &")
  eq(run("seq 5 | sed -n 2,4p"), "2\n3\n4\n")
  eq(run("seq 5 | sed '2d;$d'"), "1\n3\n4\n")
  eq(run("seq 5 | sed '/3/,$d'"), "1\n2\n")
  eq(run("seq 4 | sed -n '2!p'"), "1\n3\n4\n")
  eq(run("seq 9 | sed 3q"), "1\n2\n3\n")
  eq(run("echo /a/b | sed 's|/|:|g'"), ":a:b\n")
  eq(run("echo ab | sed -e s/a/x/ -e s/b/y/"), "xy\n")
  eq(run("echo ab | sed -n s/a/x/p"), "xb\n")
  eq(run("echo abc | sed 's/^a//;s/c$//'"), "b\n")
  put("/tmp/sedme", "# comment\nkeep\n")
  run("sed -i '/^#/d' /tmp/sedme")
  eq(file("/tmp/sedme"), "keep\n")
  has(run("sed k"), "unknown command 'k'")
  has(run("echo x | sed s/x"), "unterminated '/'")
end)

test("diff", function()
  put("/tmp/d1", "a\nb\nc\nd\ne\nf\ng\nh\ni\nj\n")
  put("/tmp/d2", "a\nb\nC\nd\ne\nf\ng\nh\ni\nj\nk\n")
  local out, rc = run("diff /tmp/d1 /tmp/d2")
  eq(rc, 1)
  eq(out, "--- /tmp/d1\n+++ /tmp/d2\n@@ -1,6 +1,6 @@\n a\n b\n-c\n+C\n d\n e\n f\n@@ -8,3 +8,4 @@\n h\n i\n j\n+k\n")
  local _, same = run("diff /tmp/d1 /tmp/d1")
  eq(same, 0)
  eq(run("diff -q /tmp/d1 /tmp/d2"), "Files /tmp/d1 and /tmp/d2 differ\n")
  put("/tmp/e1", "x\n"); put("/tmp/e2", "")
  eq(run("diff /tmp/e1 /tmp/e2"), "--- /tmp/e1\n+++ /tmp/e2\n@@ -1,1 +0,0 @@\n-x\n")
  local _, bad = run("diff /tmp/d1 /nope")
  eq(bad, 2)
end)

test("basename, dirname", function()
  eq(run("basename /etc/pacman.conf"), "pacman.conf\n")
  eq(run("basename /home/alice/notes.txt .txt"), "notes\n")
  eq(run("basename /usr/"), "usr\n")
  eq(run("dirname /etc/pacman.conf notes.txt / /a/b/"), "/etc\n.\n/\n/a\n")
end)

test("sha256sum and mktemp", function()
  put("/tmp/abc", "abc")
  eq(run("sha256sum /tmp/abc"), "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad  /tmp/abc\n")
  run("sha256sum /tmp/abc > /tmp/sums")
  eq(run("sha256sum -c /tmp/sums"), "/tmp/abc: OK\n")
  put("/tmp/abc", "abd")
  has(run("sha256sum -c /tmp/sums"), "/tmp/abc: FAILED")
  local name = run("mktemp"):gsub("\n$", "")
  ok(name:match("^/tmp/tmp%.%w%w%w%w%w%w$"), "a name from the template: " .. name)
  eq(file(name), "", "an empty file")
  local d = run("mktemp -d /tmp/dirXXXX"):gsub("\n$", "")
  ok(kernel.fs.isDirectory(d), "-d makes a directory")
end)
