-- Background jobs, ps/kill, services (systemd) and the system log.
users()
local function idle(sec) kernel.event.pull(sec) end -- the foreground waits; processes run

test("& runs the whole and-or list in the background", function()
  run("sleep 0.3 && echo bg-done &")
  has(screen(), "[1] 2", "job number on the terminal")
  local jobs = run("jobs")
  has(jobs, "Running"); has(jobs, "sleep 0.3 && echo bg-done")
  idle(1)
  shell.reportJobs()
  has(screen(), "bg-done")
  has(screen(), "Done       sleep 0.3 && echo bg-done")
  eq(#shell.jobs, 0)
end)

test("kill a job; wait", function()
  run("sleep 30 &")
  local pid = shell.jobs[#shell.jobs].pid
  has(run("ps"), "sleep 30")
  run("kill %" .. shell.jobs[#shell.jobs].id)
  eq(kernel.process.info(pid).state, "killed")
  run("sleep 0.2 &")
  run("wait")
  eq(kernel.process.info(shell.jobs[#shell.jobs].pid).state, "done")
  shell.reportJobs()
end)

test("only the owner (or root) may kill a process", function()
  local pid = as("bob", function() run("sleep 30 &"); return shell.jobs[#shell.jobs].pid end)
  as("alice", function() has(run("kill " .. pid), "permission denied") end)
  has(run("ps"), "bob")
  run("kill " .. pid)
  eq(kernel.process.info(pid).state, "killed")
  shell.jobs = {}
end)

put("/usr/bin/hellod.lua", 'local n = tonumber(arg[1]) or 3\nfor i = 1, n do print("tick " .. i) k.event.pull(0.2) end\nreturn 0\n')
put("/usr/bin/crashd.lua", 'print("starting up")\nerror("boom")\n')
put("/etc/systemd/system/hello.service", "[Unit]\nDescription=Hello ticker\n\n[Service]\nExecStart=hellod 3\n")
put("/etc/systemd/system/long.service", "[Unit]\nDescription=Long ticker\n[Service]\nExecStart=hellod 1000\nUser=bob\n")
put("/etc/systemd/system/crash.service", "[Unit]\nDescription=Crashes\n[Service]\nExecStart=crashd\nRestart=on-failure\nRestartSec=0.1\n")

test("systemctl lists units", function()
  local out = run("systemctl")
  has(out, "hello.service"); has(out, "Hello ticker"); has(out, "inactive")
end)

test("a service runs, logs its output and finishes", function()
  run("systemctl start hello")
  has(run("systemctl status hello"), "active (running)")
  idle(1.5)
  local st = run("systemctl status hello")
  has(st, "inactive")
  has(run("journalctl -u hello"), "hello: tick 3")
end)

test("a crashing service is restarted five times, its errors logged", function()
  run("systemctl start crash")
  idle(3)
  local st = run("systemctl status crash")
  has(st, "failed"); has(st, "Restarts: 5")
  has(run("journalctl -u crash"), "boom")
  has(run("journalctl -u systemd"), "giving up")
  lacks(screen(), "boom", "errors go to the log, not the screen")
end)

test("stop; runs as the unit's User", function()
  run("systemctl start long")
  local pid = require("systemd").status("long").pid
  eq(kernel.process.info(pid).user, "bob")
  run("systemctl stop long")
  has(run("systemctl status long"), "inactive")
  eq(kernel.process.info(pid).state, "killed")
end)

test("enable starts at boot; only root may control services", function()
  run("systemctl enable hello")
  eq(file("/etc/systemd/enabled"), "timesyncd\nhello\n", "timesyncd is enabled by default")
  local started = {}
  for _, r in ipairs(require("systemd").boot()) do started[r.name] = r.ok end
  eq(started.hello, true)
  as("bob", function() has(run("systemctl start hello"), "need to be root") end)
end)

test("logger, journalctl -n, dmesg", function()
  run("logger -t backup nightly backup finished")
  eq(run("journalctl -u backup"):match("backup: (.-)\n"), "nightly backup finished")
  eq(select(2, run("journalctl -n 2"):gsub("\n", "")), 2)
  has(run("dmesg"), "ByteOS test boot")
end)

test("fg waits for a job; Ctrl+C stops it", function()
  run("sleep 0.3 &")
  local out, rc = run("fg")
  eq(out, "sleep 0.3\n"); eq(rc, 0); eq(#shell.jobs, 0)
  run("sleep 30 &")
  local pid = shell.jobs[#shell.jobs].pid
  signals({ { "key_down", "kb", 0, 29 }, { "key_down", "kb", 99, 46 } })
  local _, rc2 = run("fg %" .. shell.jobs[#shell.jobs].id)
  eq(rc2, 130); eq(kernel.process.info(pid).state, "killed")
  has(run("fg"), "no current job")
end)
