-- Users, permissions, sudo, su, passwd and account management.
users()
put("/home/alice/.shrc", "# alice\n")

test("plain-text passwords are replaced by hashes on login", function()
  eq(kernel.checkPassword("root", "nope"), false)
  eq(kernel.checkPassword("root", "rootpw"), true)
  ok(file("/etc/shadow"):match("root:%$sha256%$"), "root hashed")
  has(file("/etc/shadow"), "bob:bobpw", "bob untouched until he logs in")
end)

test("a normal user cannot touch the system or other users", function()
  as("bob", function()
    eq(run("whoami"), "bob\n")
    has(run("export USER=root; whoami"), "bob")
    has(run("cat /etc/shadow"), "permission denied")
    has(run("mkdir /etc/evil"), "permission denied")
    has(run("rm /bin/ls.lua"), "permission denied")
    has(run("mkdir /home/bob/../alice/evil"), "permission denied")
    has(run("echo x > /etc/x"), "permission denied")
    has(run("pacman -S cowsay"), "unless you are root")
    eq(select(2, run("mkdir /home/bob/projects; mkdir /tmp/bob")), 0)
    local okMount = kernel.fs.mount("/evil", {})
    eq(okMount, nil, "mount refused")
  end)
  eq(file("/bin/ls.lua") ~= nil, true)
  eq(kernel.user(), "root", "back to root")
end)

test("sudo: wheel only, own password, remembered, -k", function()
  as("bob", function()
    answers({ "bobpw" })
    has(run("sudo whoami"), "not in the sudoers file")
  end)
  as("alice", function()
    answers({ "wrong", "alicepw" })
    local out = run("sudo whoami")
    has(out, "Sorry, try again."); has(out, "root")
    eq(run("sudo whoami"), "root\n", "no password the second time")
    run("sudo -k")
    answers({ "alicepw" })
    eq(run("sudo whoami"), "[sudo] password for alice: root\n")
  end)
  has(file("/var/log/messages"), "sudo: alice : PWD=")
end)

test("passwd: own password with the current one; root sets any", function()
  as("bob", function()
    answers({ "wrong", "n1", "n1" })
    has(run("passwd"), "Authentication failure")
    answers({ "bobpw", "bob2", "bob2" })
    has(run("passwd"), "updated successfully")
    has(run("passwd alice"), "may not view or modify")
  end)
  eq(kernel.checkPassword("bob", "bob2"), true)
  eq(kernel.checkPassword("bob", "bobpw"), false)
end)

test("useradd, usermod, userdel, id, groups", function()
  as("alice", function()
    answers({ "alicepw" })
    has(run("sudo useradd -m -G wheel carol"), "created")
    has(run("useradd mallory"), "Permission denied")
    answers({ "carolpw", "carolpw" })
    has(run("sudo passwd carol"), "updated successfully")
    eq(run("id carol"), "uid=1002(carol) gid=100(users) groups=10(wheel),100(users)\n")
    run("sudo usermod -rG wheel carol")
    eq(run("groups carol"), "users\n")
    ok(file("/home/carol/.shrc"), "home made from /etc/skel")
    run("sudo userdel -r carol")
    has(run("id carol"), "no such user")
  end)
  eq(file("/home/carol/.shrc"), nil, "home removed")
end)

test("su starts a shell as another user; exit comes back", function()
  as("alice", function()
    answers({ "bob2" })
    keys({ "whoami", "<enter>", "exit", "<enter>" })
    run("su bob")
    has(screen(), "bob@byteos")
    eq(run("whoami"), "alice\n")
  end)
end)
