-- Users, permissions, sudo, su, passwd and account management.
users()
put("/home/alice/.shrc", "# alice\n")

test("plain-text passwords are replaced by hashes on login", function()
  eq(kernel.checkPassword("root", "nope"), false)
  eq(kernel.checkPassword("root", "rootpw"), true)
  ok(file("/etc/shadow"):match("root:%$sha256%$"), "root hashed")
  has(file("/etc/shadow"), "bob:bobpw", "bob untouched until he logs in")
end)

test("a normal user cannot touch the system or other users", function()
  as("bob", function()
    eq(run("whoami"), "bob\n")
    has(run("export USER=root; whoami"), "bob")
    has(run("cat /etc/shadow"), "permission denied")
    has(run("mkdir /etc/evil"), "permission denied")
    has(run("rm /bin/ls.lua"), "permission denied")
    has(run("mkdir /home/bob/../alice/evil"), "permission denied")
    has(run("echo x > /etc/x"), "permission denied")
    has(run("pacman -S cowsay"), "unless you are root")
    eq(select(2, run("mkdir /home/bob/projects; mkdir /tmp/bob")), 0)
    local okMount = kernel.fs.mount("/evil", {})
    eq(okMount, nil, "mount refused")
  end)
  eq(file("/bin/ls.lua") ~= nil, true)
  eq(kernel.user(), "root", "back to root")
end)

test("sudo: wheel only, own password, remembered, -k", function()
  as("bob", function()
    answers({ "bobpw" })
    has(run("sudo whoami"), "not in the sudoers file")
  end)
  as("alice", function()
    answers({ "wrong", "alicepw" })
    local out = run("sudo whoami")
    has(out, "Sorry, try again."); has(out, "root")
    eq(run("sudo whoami"), "root\n", "no password the second time")
    run("sudo -k")
    answers({ "alicepw" })
    eq(run("sudo whoami"), "[sudo] password for alice: root\n")
  end)
  has(file("/var/log/messages"), "sudo: alice : PWD=")
end)

test("passwd: own password with the current one; root sets any", function()
  as("bob", function()
    answers({ "wrong", "n1", "n1" })
    has(run("passwd"), "Authentication failure")
    answers({ "bobpw", "bob2", "bob2" })
    has(run("passwd"), "updated successfully")
    has(run("passwd alice"), "may not view or modify")
  end)
  eq(kernel.checkPassword("bob", "bob2"), true)
  eq(kernel.checkPassword("bob", "bobpw"), false)
end)

test("useradd, usermod, userdel, id, groups", function()
  as("alice", function()
    answers({ "alicepw" })
    has(run("sudo useradd -m -G wheel carol"), "created")
    has(run("useradd mallory"), "Permission denied")
    answers({ "carolpw", "carolpw" })
    has(run("sudo passwd carol"), "updated successfully")
    eq(run("id carol"), "uid=1002(carol) gid=100(users) groups=10(wheel),100(users)\n")
    run("sudo usermod -rG wheel carol")
    eq(run("groups carol"), "users\n")
    ok(file("/home/carol/.shrc"), "home made from /etc/skel")
    run("sudo userdel -r carol")
    has(run("id carol"), "no such user")
  end)
  eq(file("/home/carol/.shrc"), nil, "home removed")
end)

test("su starts a shell as another user; exit comes back", function()
  as("alice", function()
    answers({ "bob2" })
    keys({ "whoami", "<enter>", "exit", "<enter>" })
    run("su bob")
    has(screen(), "bob@byteos")
    eq(run("whoami"), "alice\n")
  end)
end)

test("ls -l shows owners and modes from where files are", function()
  local out = run("ls -l /etc/passwd /home/alice/.shrc /etc/shadow")
  has(out, "-rw-r--r--  root root"); has(out, "-rw-r--r--  alice users"); has(out, "-rw-------  root root")
  has(run("ls -l /"), "drwxr-xr-x  root root")
end)

test("chmod: owners guard their files, directories guard what is inside", function()
  as("alice", function()
    eq(select(2, run("chmod 600 /home/alice/.shrc")), 0)
    has(run("ls -l /home/alice/.shrc"), "-rw-------  alice")
    eq(run("cat /home/alice/.shrc"), "# alice\n", "the owner still reads it")
  end)
  as("bob", function()
    has(run("cat /home/alice/.shrc"), "permission denied")
    has(run("chmod 666 /home/alice/.shrc"), "permission denied")
    has(run("chmod 777 /etc/passwd"), "permission denied")
  end)
  as("alice", function()
    run("chmod u+x,go+r /home/alice/.shrc")
    eq(kernel.fs.stat("/home/alice/.shrc").mode, tonumber("744", 8))
    run("mkdir /home/alice/private; echo s > /home/alice/private/s; chmod go-rx /home/alice/private")
  end)
  as("bob", function()
    eq(run("cat /home/alice/.shrc"), "# alice\n")
    has(run("cat /home/alice/private/s"), "permission denied", "no x on the directory")
  end)
  has(run("chmod 7z /tmp"), "invalid mode")
end)

test("chown: shared directories for a group; entries follow mv and rm", function()
  run("mkdir /srv; mkdir /srv/team; chown alice:wheel /srv/team; chmod 775 /srv/team")
  as("alice", function()
    has(run("chown bob /home/alice/.shrc"), "permission denied", "only root gives files away")
  end)
  as("alice", function() eq(select(2, run("echo hi > /srv/team/a")), 0, "alice owns it") end)
  as("bob", function()
    has(run("echo hi > /srv/team/b"), "permission denied", "bob is not in wheel")
    eq(run("cat /srv/team/a"), "hi\n", "others may still read")
  end)
  has(run("chown nobody /srv/team"), "no such user")
  has(run("chown :nogroup /srv/team"), "no such group")
  has(file("/var/lib/perms"), "775 alice wheel /srv/team")
  run("mv /srv/team /srv/crew")
  has(file("/var/lib/perms"), "/srv/crew"); lacks(file("/var/lib/perms"), "/srv/team")
  run("rm -r /srv/crew")
  lacks(file("/var/lib/perms"), "/srv/crew")
  run("chown -R bob /home/alice/private")
  eq(kernel.fs.stat("/home/alice/private/s").owner, "bob")
end)

test("chmod -R writes /var/lib/perms once, not once per file", function()
  run("mkdir /srv; mkdir /srv/many; for I in $(seq 8); echo x > /srv/many/f$I; end")
  local writes = 0
  local open = kernel.fs.open
  kernel.fs.open = function(p, m)
    if p == "/var/lib/perms" and m == "w" then writes = writes + 1 end
    return open(p, m)
  end
  run("chmod -R 700 /srv/many")
  kernel.fs.open = open
  eq(writes, 1)
  eq(kernel.fs.stat("/srv/many/f8").mode, tonumber("700", 8))
end)
