-- ByteShell: parsing, variables, aliases, pipes, redirection, wildcards, scripts.
put("/tmp/a.txt", "hello\nworld\n")

test("quotes, escapes, variables and ~", function()
  _G.NAME = "World"
  local w = shell.tokenize([[echo "hi $NAME" 'no $NAME' ${NAME}x a\ b ~ $UNSET end]])
  eq(table.concat(w, "|"), "echo|hi World|no $NAME|Worldx|a b|/home/root|end")
  eq(#shell.tokenize('"$UNSET" x'), 2, "a quoted empty variable stays a word")
end)

test("USER and HOME are read-only, names must be UPPERCASE", function()
  local out = run("export USER=root; export term=x; _G=x; FOO=bar; echo $FOO")
  has(out, "USER: read-only variable")
  has(out, "'term': not a valid variable name")
  has(out, "'_G': not a valid variable name")
  has(out, "bar")
  eq(type(term), "table", "term library untouched")
end)

test("; && || not and $status", function()
  local out = run("nosuch || echo fallback; echo yes && echo and-ok; not echo x || echo inverted; nosuch; echo s=$status q=$?")
  has(out, "fallback"); has(out, "and-ok"); has(out, "inverted"); has(out, "s=127 q=127")
end)

test("aliases, including self-reference and loops", function()
  local out = run("alias greet='echo hello $USER'; greet there; alias echo='echo [a]'; echo self; unalias echo; alias a=b; alias b=a; a")
  has(out, "hello root there"); has(out, "[a] self"); has(out, "Unknown command: a")
end)

test("pipes and redirection", function()
  eq(run("cat /tmp/a.txt | grep o | wc -l"), "      2\n")
  run("echo one > /tmp/r.txt; echo two >> /tmp/r.txt")
  eq(file("/tmp/r.txt"), "one\ntwo\n")
  eq(run("grep -n o < /tmp/a.txt"), "1:hello\n2:world\n")
  run("alias x='echo y'; alias > /tmp/al")
  has(file("/tmp/al"), "alias x='echo y'")
  has(run("echo x >"), "missing file name after >")
  has(run("| grep x"), "empty command in a pipe")
  eq(run([[echo 'a|b' "c > d"]]), "a|b c > d\n", "quoted operators are text")
end)

test("wildcards", function()
  has(run("echo /bin/s*.lua"), "/bin/sh.lua /bin/shutdown.lua")
  eq(run([[echo '/bin/s*' /bin/w\*]]), "/bin/s* /bin/w*\n", "quoted or escaped: literal")
  eq(run("echo /nomatch*"), "/nomatch*\n", "no match: kept")
end)

test("scripts with arguments and exit", function()
  put("/tmp/s.sh", '#!/bin/sh\necho "$0 got $# args: $@"\necho first=$1\nsh /tmp/count.sh $@\nexit 3\necho not reached\n')
  put("/tmp/count.sh", "echo count=$#\n")
  local out, rc = run("/tmp/s.sh a b c")
  has(out, "/tmp/s.sh got 3 args: a b c"); has(out, "first=a"); has(out, "count=3"); lacks(out, "not reached")
  eq(rc, 3, "exit status")
  has(run("sh -c 'echo inner; exit 4'; echo after=$?"), "after=4")
  run("/tmp/s.sh q > /tmp/out")
  eq(select(2, file("/tmp/out"):gsub("\n", "")), 3, "a script's output can be redirected")
end)

test("auto-cd and cd -", function()
  _G.PWD = "/etc"
  run("..")
  eq(_G.PWD, "/")
  eq(run("cd -"), "/etc\n")
  eq(_G.PWD, "/etc")
end)

test("Ctrl+C stops a waiting program and the rest of the line", function()
  put("/tmp/wait.lua", "while true do k.event.pull(1) end\n")
  signals({ { "key_down", "kb", 0, 29 }, { "key_down", "kb", 99, 46 } })
  local out = run("/tmp/wait.lua; echo should-not-run")
  lacks(out, "should-not-run")
  eq(shell.status, 130)
end)

test("history file: dedup, leading space, per user", function()
  put("/home/root/.byteshell_history", "ls\necho a\nls\n")
  shell.loadHistory()
  eq(table.concat(shell.history, ","), "echo a,ls")
  shell.addHistory("echo b")
  shell.addHistory(" secret")
  shell.addHistory("echo a")
  eq(table.concat(shell.history, ","), "ls,echo b,echo a")
  lacks(file("/home/root/.byteshell_history"), "secret")
end)
